#! /usr/bin/env bash

target=$1
appname=${1//-/_}

CONC=$HOME/Programs/install/conceptual/sst
CC=sstcc 
#CONC=$HOME/Programs/install/conceptual/mpi
#CC=mpicc

$CONC/bin/ncptl $1.ncptl --backend=c_mpi --no-compile > $1.c

SSTMAC_SKELETONIZE=1 \
 $CC -O3 -o run$1 \
 -Dsstmac_app_name=$appname \
 -Wno-unused-value \
 -L$CONC/lib -lncptl \
 -I$CONC/include \
 $1.c 

